source 'http://rubygems.org'

gem 'rails', '3.1.1'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

#JQuery
gem 'jquery-rails'

#Spine.JS
gem 'spine-rails'
gem 'eco' 

gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'